apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::581734543281:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WP9QRDFKUOH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::581734543281:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-04T15:27:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1931"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 759915b7-1e6a-4763-b733-fedf599733f9
